services:
  postgres:
    image: postgres:14-alpine
    container_name: node-postgresql
    env_file:
      - .env.development
    ports:
      - 5432:5432
    volumes:
      - pgdata_node:/var/lib/postgresql/data
    networks:
      - tours_node-network
  
  pgadmin:
    image: dpage/pgadmin4
    user: root
    container_name: node-pgadmin
    env_file:
      - .env.dev
    ports:
      - 8080:80
    volumes:
      - pgadmin_node:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - tours_node-network

volumes:
  pgdata_node:
  pgadmin_node:

networks:
  tours_node-network:
    driver: bridge